import "./globals.css";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TomatoGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/tomato-grotesk-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/tomato-grotesk-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/tomato-grotesk-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/tomato-grotesk-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/tomato-grotesk-black.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/tomato-grotesk-black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={"bg-primary-white/10 antialiased font-primary"}>
        {children}
      </body>
    </html>
  );
}
